### ISSUE TITLE
Python SoapySDR app stuck every 2nd launch

### ISSUE THREAD

**Issue by dmitryelj** [pothosware/SoapyUHD#18]
Hi all,

After last update to UHD 3.11 and PothosSDR-2018.07.20-vc14-x64.exe, console python app is not starting every second run.
Code to reproduce: test.py
```
import SoapySDR

sdr = SoapySDR.Device({'driver': 'uhd'})
rates = sdr.listSampleRates(SoapySDR.SOAPY_SDR_TX, 0)
print("TX Rates:\n", rates)
```

**Run**: python test.py

**Output** 
1st run: all ok
[INFO] [UHD] Win32; Microsoft Visual C++ version 14.0; Boost_106700; UHD_3.11.1.0-0-gad6b0935
[INFO] [b200_impl.cpp:382] [B200] Detected Device: B210
[INFO] [B200] Detected Device: B210
[INFO] [b200_impl.cpp:429] [B200] Operating over USB 3.
...

2nd run: app stuck at the 1st line
[INFO] [UHD] Win32; Microsoft Visual C++ version 14.0; Boost_106700; UHD_3.11.1.0-0-gad6b0935

Nothing more in the output.  Ctrl+C does not close the app, needs to restart the console.

Sometimes it happens only after 2-3 launches.

**Comment by guruofquality** [comment]
I will be updating the installer as soon as the soapybladerf updates are ready. I removed a potential UHD patch that could have caused this and UHD guys will take over upstreaming the patch and testing it. So hopefully this is fixed by either that or whatever UHD updates come in the next build. Keep your eyes peeled for a new installer.
