### ISSUE TITLE
Having trouble connecting to USRP N210 with SoapyUHD

### ISSUE THREAD

**Issue by EricGaulke** [pothosware/SoapyUHD#31]
Hello, I am trying to use SoapyUHD to connect to a USRP N210. I am able to connect to the N210 using uhd_find_devices, but I am not able to connect using SoapySDRUtil --probe="driver=uhd,type=usrp2". I believe I have installed SoapyUHD correctly since I can see it in the available factories section when using SoapySDRUtil --info. Attached is a screeshot of the output of SoapySDRUtil --probe="driver=uhd,type=usrp2". Any help would be appreciated.
![log](https://user-images.githubusercontent.com/34021483/74978797-37acb080-53e2-11ea-93cd-3fc644f0f1c1.png)

**Comment by guruofquality** [comment]
Sounds like everything is correct.

So what is the output of `SoapySDRUtil --info`

And more importantly, what about `SoapySDRUtil --find` ?

**Comment by EricGaulke** [comment]
![info](https://user-images.githubusercontent.com/34021483/74979363-59f2fe00-53e3-11ea-8da5-2c508c537c3f.png)
![find](https://user-images.githubusercontent.com/34021483/74979373-5e1f1b80-53e3-11ea-9e5a-76debc00420b.png)

**Comment by guruofquality** [comment]
I cant think of why uhd_find_devices linked to the same libuhd as SoapyUHD would not see the devices. Unless maybe theres more than one libuhd (one working and one not)

Do you see that UHD version string printed at the end? Does `uhd_find_devices` report that same version string?

**Comment by EricGaulke** [comment]
Yes it does
![uhd](https://user-images.githubusercontent.com/34021483/74989809-52892000-53f6-11ea-8bd9-77a1c68a8202.png)

**Comment by guruofquality** [comment]
So I dont really know what the issue could be but if you are interested in debugging it. This is what I would try to do:

1) remove just the soapy uhd package from the apt package repository
2) since you are using debs, install libuhd-dev and libsoapysdr-dev
3) build SoapyUHD from souce
4) Just add prints: https://github.com/pothosware/SoapyUHD/blob/master/SoapyUHDDevice.cpp#L1042
4a) find_uhd should be called
4b) and uhd::device::find should be returning something

Just another idea, sometimes issues like this boil down to just package weirdness. and sometimes in this ecosystem, its easier to install from source. You might try installing SoapySDR from source as well, just remove the package from apt before doing it.

hope that helps

**Comment by EricGaulke** [comment]
I added a print statement inside find_uhd in SoapyUHDDevice.cpp, but it seems find_uhd isn't being called at all. Any idea why this would happen?

**Comment by EricGaulke** [comment]
Fixed it. I uninstalled and reinstalled UHD and SoapyUHD from source and it fixed it somehow. Thanks for the help.
